### ISSUE TITLE
Scroll by full size

### ISSUE THREAD

**Issue by chiefcll** [lightning-js/ui-components#169]
@slhay28 

I have a viewport of say 3 items and when the bottom is reached I want the items to scroll to the next 3 items rather than one at a time when the bottom of the list is reached

What do you think about implementing that logic? Basically get to end and move the whole list by its viewport size?

**Comment by anthony9187** [comment]
Closing this as I believe it's resolved, but we can re-open it in the new repo if it's still appearing
