### ISSUE TITLE
bug: Column children in wrong position on scroll

### ISSUE THREAD

**Issue by CosmaVergari** [lightning-js/ui-components#86]
In the Solid Column component, with scroll="edge" the unselected items get randomly misplaced when scrolling down (the focused element is in red)

<img width="383" alt="Screenshot 2024-02-26 alle 17 52 33" src="https://github.com/lightning-js/ui-components/assets/49166275/b4ffc7fa-2811-49d5-9ec4-795019a2b73c">

If no scrolling is triggered, the elements go to the correct position after they have received focus:

<img width="383" alt="Screenshot 2024-02-26 alle 17 59 11" src="https://github.com/lightning-js/ui-components/assets/49166275/3f8da69b-ee2b-44c5-badf-64d0b4d4a3c0">

When using scroll="auto" or "always" some elements are crammed above the focused element:

<img width="376" alt="Screenshot_2024-02-26_alle_16 53 46" src="https://github.com/lightning-js/ui-components/assets/49166275/0e49e9cb-5d51-4c62-bf84-78c7cb680489">

Here is a code snippet of the example I'm running:
```Typescript
<Column
	scroll="edge"
	style={{ Container: { width: 590, height: 932, x: 30, y: 0, gap: 20 } }}
>
	<For each={props.seasons}>
		{(season) => {
			return <Text style={buttonStyles.Label}>{season.seasonTitle}</Text>;
		}}
	</For>
</Column>
```

Here is `buttonStyles.Label`:
```Typescript
Label: {
	fontFamily: "Regular",
	fontSize: 28,
	lineHeight: 36,
	letterSpacing: 0.5,
	maxLines: 1,
	overflowSuffix: "...",
	contain: "width",
	color: 0xfafafaff,
	focus: {
		color: 0xff0000ff,
	},
	x: 30,
	y: 12,
        width: 500,
},
```

It seems to be some positioning problem affecting both lng/solid and the renderer

**Comment by anthony9187** [comment]
Thanks for bringing this to our attention! We'll take a look at this and keep you updated on our progress

**Comment by anthony9187** [comment]
@CosmaVergari I'm going to close this issue as I believe this has been resolved and we've moved the repo to a new location. If you're still experiencing this problem please open an issue here: https://github.com/rdkcentral/solid-ui
