### ISSUE TITLE
bug: Row/Column with scroll="always" and selected > 0 - Solid

### ISSUE THREAD

**Issue by pecoram** [lightning-js/ui-components#90]
With scroll="always" and selected > 0 the **x** of the Row/Column is not set correctly

![image](https://github.com/lightning-js/ui-components/assets/33352553/d91a2aa5-7502-4d32-9404-82a35185ff20)

I advice a function similar to this

```
	function onCreate(this: ElementNode): void {
		if (
			props.selected &&
			props.scroll !== "none" &&
			this?.onSelectedChanged &&
			this.children?.[props.selected]
		) {
			this.onSelectedChanged.call(
				this,
				this,
				this.children[props.selected] as ElementNode,
				props.selected,
				undefined,
			);
		}
	}
```

...
onCreate={onCreate}

**Comment by slhay28** [comment]
Hi @pecoram, thanks for opening this issue. We have added the scrolling logic on creation of the components in https://github.com/lightning-js/ui-components/pull/92 . Thanks again.
