### ISSUE TITLE
Missing onCreate chain functions

### ISSUE THREAD

**Issue by pecoram** [lightning-js/ui-components#95]
https://github.com/lightning-js/ui-components/blob/4ea7429cd93a3cfc019aa93fac3c5ec49aed8db6/src/packages/solid/components/Column/Column.tsx#L76-L84

In the Column and in the Row chainFunctions are missing

`onCreate={chainFunctions(onCreate, props.onCreate)}`

**Comment by chiefcll** [comment]
Good catch @slhay28 - we'll get this in shortly
